In [10]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

import warnings
warnings.simplefilter("ignore", UserWarning)

## Part 1 - simple ratings:

In [46]:
raw_ratings = pd.read_excel('Assignment 5.xlsx', sheet_name='Ratings').fillna(0)
raw_ratings

,User,1: Toy Story (1995),1210: Star Wars: Episode VI - Return of the Jedi (1983),356: Forrest Gump (1994),"318: Shawshank Redemption, The (1994)","593: Silence of the Lambs, The (1991)",3578: Gladiator (2000),260: Star Wars: Episode IV - A New Hope (1977),2028: Saving Private Ryan (1998),296: Pulp Fiction (1994),...,2916: Total Recall (1990),780: Independence Day (ID4) (1996),541: Blade Runner (1982),1265: Groundhog Day (1993),"2571: Matrix, The (1999)",527: Schindler's List (1993),"2762: Sixth Sense, The (1999)",1198: Raiders of the Lost Ark (1981),34: Babe (1995),Mean
0,755,2.00000,5.000000,2.000000,0.000000,4.0000,4.000000,1.000000,2.000000,0.000000,...,0.00000,5.00000,2.000000,5.000000,4.000000,2.000000,5.000000,0.00000,0.000000,3.200000
1,5277,1.00000,0.000000,0.000000,2.000000,4.0000,2.000000,5.000000,0.000000,0.000000,...,2.00000,2.00000,0.000000,2.000000,0.000000,5.000000,1.000000,3.00000,0.000000,2.769231
2,1577,0.00000,0.000000,0.000000,5.000000,2.0000,0.000000,0.000000,0.000000,0.000000,...,1.00000,4.00000,4.000000,1.000000,1.000000,2.000000,3.000000,1.00000,3.000000,2.333333
3,4388,2.00000,3.000000,0.000000,0.000000,0.0000,1.000000,0.000000,3.000000,4.000000,...,4.00000,0.00000,3.000000,5.000000,0.000000,5.000000,1.000000,1.00000,2.000000,2.833333
4,1202,0.00000,3.000000,4.000000,1.000000,4.0000,1.000000,4.000000,4.000000,0.000000,...,1.00000,0.00000,4.000000,0.000000,3.000000,5.000000,5.000000,0.00000,0.000000,3.214286
5,3823,3.00000,4.000000,4.000000,4.000000,0.0000,0.000000,2.000000,1.000000,4.000000,...,2.00000,4.00000,0.000000,1.000000,0.000000,0.000000,3.000000,0.00000,2.000000,3.071429
6,5448,0.00000,0.000000,3.000000,1.000000,1.0000,4.000000,4.000000,5.000000,2.000000,...,0.00000,0.00000,3.000000,0.000000,1.000000,0.000000,0.000000,5.00000,2.000000,2.666667
7,5347,2.00000,0.000000,0.000000,0.000000,3.0000,2.000000,4.000000,0.000000,3.000000,...,2.00000,1.00000,2.000000,4.000000,0.000000,1.000000,3.000000,5.00000,0.000000,2.666667
8,4117,4.00000,1.000000,0.000000,4.000000,2.0000,4.000000,5.000000,4.000000,0.000000,...,0.00000,1.00000,0.000000,5.000000,0.000000,0.000000,0.000000,0.00000,5.000000,3.166667
9,2765,4.00000,2.000000,0.000000,5.000000,3.0000,0.000000,4.000000,3.000000,4.000000,...,0.00000,2.00000,0.000000,0.000000,2.000000,5.000000,1.000000,0.00000,0.000000,3.181818
10,5450,5.00000,1.000000,5.000000,0.000000,0.0000,5.000000,2.000000,0.000000,0.000000,...,3.00000,2.00000,0.000000,0.000000,1.000000,0.000000,2.000000,1.00000,4.000000,2.818182
11,139,2.00000,5.000000,2.000000,0.000000,0.0000,0.000000,3.000000,0.000000,1.000000,...,0.00000,3.00000,0.000000,2.000000,5.000000,0.000000,0.000000,0.00000,2.000000,2.800000
12,1940,4.00000,0.000000,0.000000,5.000000,4.0000,0.000000,2.000000,5.000000,0.000000,...,2.00000,4.00000,0.000000,3.000000,0.000000,0.000000,0.000000,5.00000,0.000000,3.777778
13,3118,3.00000,0.000000,3.000000,0.000000,2.0000,0.000000,3.000000,0.000000,0.000000,...,1.00000,2.00000,2.000000,3.000000,5.000000,1.000000,0.000000,0.00000,0.000000,2.636364
14,4656,2.00000,4.000000,0.000000,0.000000,5.0000,5.000000,4.000000,0.000000,3.000000,...,1.00000,3.00000,0.000000,2.000000,0.000000,3.000000,0.000000,3.00000,1.000000,3.153846
15,4796,0.00000,0.000000,1.000000,0.000000,3.0000,2.000000,0.000000,2.000000,0.000000,...,0.00000,2.00000,0.000000,0.000000,2.000000,2.000000,4.000000,3.00000,4.000000,2.583333
16,6037,2.00000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,2.000000,...,0.00000,3.00000,0.000000,3.000000,4.000000,0.000000,0.000000,0.00000,0.000000,2.666667
17,3048,4.00000,5.000000,1.000000,5.000000,1.0000,1.000000,4.000000,0.000000,5.000000,...,0.00000,0.00000,4.000000,0.000000,0.000000,2.000000,1.000000,2.00000,5.000000,3.076923
18,4790,2.00000,1.000000,3.000000,0.000000,0.0000,4.000000,5.000000,1.000000,3.000000,...,1.00000,0.00000,0.000000,0.000000,2.000000,0.000000,0.000000,0.00000,0.000000,2.545455
19,4489,2.00000,2.000000,2.000000,4.000000,5.0000,0.000000,1.000000,3.000000,2.000000,...,0.00000,4.00000,5.000000,5.000000,4.000000,3.000000,5.000000,3.00000,0.000000,3.117647
20,L2,11.83216,11.661904,9.899495,12.409674,12.4499,11.357817,14.247807,10.908712,10.630146,...,6.78233,11.74734,10.148892,12.529964,11.045361,11.661904,11.224972,10.86278,10.392305,0.000000

### Fillind out matrix dataframe based on cosine similarity, derived from user ratings:

In [63]:
matrix_df = pd.read_excel('Assignment 5.xlsx', sheet_name='Matrix', index_col=0)
fill_index, fill_cols = matrix_df.index, matrix_df.columns
matrix_df = pd.DataFrame(cosine_similarity(raw_ratings.values[0:-1,1:-1].T),
                        index = fill_index, columns = fill_cols)

### Top five similar movies to Toy story:

In [67]:
matrix_df['1: Toy Story (1995)'].sort_values(ascending=False)[1:6]

260: Star Wars: Episode IV - A New Hope (1977)    0.747409
780: Independence Day (ID4) (1996)                0.690665
296: Pulp Fiction (1994)                          0.667846
318: Shawshank Redemption, The (1994)             0.667424
1265: Groundhog Day (1993)                        0.661016
Name: 1: Toy Story (1995), dtype: float64

### Calculating user-item scores: